---

version: "3.6"

services:
  jenkins-master:
    container_name: jenkins-master
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    file: ./secrets/jenkins-user
  jenkins-pass:
    file: ./secrets/jenkins-pass
